### ISSUE TITLE
Send message dont work

### ISSUE THREAD

**Issue by marczu83** [UlisesGascon/n8n-nodes-synology-chat#5]
Get this error 
NodeOperationError: Request not send
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-synology-chat/nodes/SynologyChat/SynologyChat.node.ts:151:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:672:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:652:53

**Comment by UlisesGascon** [comment]
Hi @marczu83,

Could you please provide additional information? Specifically, a code snippet, the Node.js version, and the OS version would be greatly appreciated. This will help me in reproducing the bug for further investigation.

Thank you!

**Comment by marczu83** [comment]
Hey, I'm using the gui in n8n. I added credentials and when I try to send a message to synology chat I get this message. I'm using the current version of n8n selfhosted on docker.

![image](https://github.com/UlisesGascon/n8n-nodes-synology-chat/assets/78848931/d3642191-fe1e-45dd-afbd-dc80f0d7ae15)
